### PR TITLE
Fix background color changing panel layout

### PR DESCRIPTION
**Pull request by The-Phoenics**
# Issue Title: Background changing panel breaking layout
*resolve issue:* #215 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## Screenshots of changes made
second
first

### CODE REVIEW

**Comment by The-Phoenics** [comment]
Hey @0xabdulkhalid 
I've made necessary changes to fix the styling problem with Background color changing panel. Can you please review the PR?

**Comment by singodiyashubham87** [comment]
@The-Phoenics Merge main branch & push commit.

**Comment by The-Phoenics** [comment]
Done :)  @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@The-Phoenics Fix the conflicts, So that I can merge this PR.

**Comment by The-Phoenics** [comment]
Done! Can you please check again? @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@The-Phoenics Not resolved.

**Comment by The-Phoenics** [comment]
Hey @singodiyashubham87 
Can you please check again?

**Comment by singodiyashubham87** [comment]
@The-Phoenics While resolving the conflicts, you have removed the code added by a previous PR to fix an issue which was that after selecting any shape the user was not able to select pencil again, & the issue is again there in your PR, fix it.

**Comment by The-Phoenics** [comment]
@singodiyashubham87 Can you please mention that PR?

**Comment by singodiyashubham87** [comment]
@The-Phoenics https://github.com/singodiyashubham87/Draw-it-out/pull/284
By the way, I recommend you to just copy your changes somewhere else & create a fresh clone of the updated repository & the paste your changes & create a new fresh PR.

**Comment by The-Phoenics** [comment]
@singodiyashubham87 Can you check again?

**Comment by singodiyashubham87** [comment]
@The-Phoenics The PR has conflicts.

**Comment by The-Phoenics** [comment]
@singodiyashubham87 Can you check once again?

**Comment by The-Phoenics** [comment]
Left panel has been removed in main branch @singodiyashubham87 ?

**Comment by singodiyashubham87** [comment]
@The-Phoenics It has been shifted to the bottom, just check the deployed app once at **https://draw-it-out.vercel.app**

**Comment by The-Phoenics** [comment]
I think this PR was nothing but waste of time, if the idea was to move it to the bottom. I didn't got notified or anything about that!

**Pull request closed without merging**
