### PR TITLE
Added dockerfile and docker-compose

### PR DESCRIPTION
**Pull request by Ratangulati**
# Issue Title: Adding Dockerfile and docker-compose
*resolve issue:* #353 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Ratangulati** [comment]
@singodiyashubham87 I have created the PR for the following issue. Please review my PR.

**Comment by singodiyashubham87** [comment]
@Ratangulati What's the need for a **docker-compose.yml** file when we have to spin up only a single container?
We can have just a Dockerfile only.

**Comment by Ratangulati** [comment]
> @Ratangulati What's the need for a **docker-compose.yml** file when we have to spin up only a single container? We can have just a Dockerfile only.

You are right we only need a docker as docker-compose is used for multi container. I added docker-compose for future aspects of the project. I can remove the docker compose if you need it.

**Comment by singodiyashubham87** [comment]
@Ratangulati Yes, remove compose & just keep Dockerfile.

**Comment by Ratangulati** [comment]
@singodiyashubham87 I have removed the docker-compose and added the required documentation.
Thankyou.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Ratangulati Well Done, Keep contributing :)

**Pull request merged**
