### PR TITLE
icons aligned in straight line

### LINKED ISSUE #435: [Bug]: Icons not aligned perfectly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we click on eye icon, all the icons are not aligned in line correctly.

### Expected behavior

I can align them correctly. Please assign me this issue under GSSOC'24.

### Add ScreenShots

Screenshot 2024-07-02 204242

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ankiiitagupta**
# Issue Title: 
closes #435 

## Type of change ☑️
Aligned icons in straight line

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

https://github.com/singodiyashubham87/Draw-it-out/assets/108889476/c4aeaed1-2432-4e87-953f-b689d03e1d91

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@ankiiitagupta It should not also come over the canvas, kindly fix that too.

**Comment by ankiiitagupta** [comment]
@singodiyashubham87 Hey, I have fixed that too, you can check.

**Comment by ankiiitagupta** [comment]
@singodiyashubham87 if I will not decrease the width then only way is to decrease the icons dimension, will that be okay??

**Comment by singodiyashubham87** [comment]
@ankiiitagupta Do one thing, just reset your last commit which you made, I'll fix the overflow issue.

**Comment by ankiiitagupta** [comment]
@singodiyashubham87 I have already reverted my last commit in which I changed the width of the canvas.

Screenshot 2024-07-11 185058

**Comment by singodiyashubham87** [comment]
@ankiiitagupta There is a syntax error in your code & merge conflicts too.
image

**Comment by ankiiitagupta** [comment]
@singodiyashubham87 you can check it

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
