### PR TITLE
Solution for Issue#58

### PR DESCRIPTION
**Pull request by thatsyogeshjjr**
# Issue Title: 
*resolve issue:* #58 

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## Changes made:
- [x] a popup for file save type (will save time in future file type additions as well)
- [x] Currently available export types: PNG, JPG
- [x] added a transparent background fill option

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Kindly add a working video of the changes that you made.

**Comment by thatsyogeshjjr** [comment]
https://github.com/singodiyashubham87/Draw-it-out/assets/69074180/93c6106d-b309-469a-9a8e-33b7b903863e

The first image saved is saved over a transparent background (w/o the smiley) displaying ability of the solution to save images as transparent png(s). The next two images are saved over a white background in jpg and png formats.

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Kindly resolve the conflicts.

**Review by singodiyashubham87 — CHANGES_REQUESTED** [review]
@thatsyogeshjjr Use let instead of var and there is syntax error in your code you have misplace div instead of button, kindly fix that.

**Comment by thatsyogeshjjr** [comment]
Wait,I have a better way to integrate it with the recent project changes, I'll be back with a new PR

**Comment by thatsyogeshjjr** [comment]
@singodiyashubham87  I just made a new PR #139
The updates now integrate better with the newer UI

**Pull request closed without merging**
