### PR TITLE
 Made The Website "Canvas Responsive"

### LINKED ISSUE #427: [Bug]: The Website "Canvas" Is "Not Responsive"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @singodiyashubham87 

The Website "Canvas" Is "Not Responsive"

image

Could you please assign this issue to me under GSSOC24 ?

### Expected behavior

It should be "Responsive".

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
Hey @singodiyashubham87 issue closes #427 

I have made the website Canvas Responsive.

image

## Type of change ☑️

What sort of change have you made: 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@RadhikaMalpani1702 Make the canvas width 90% of the clientWidth, so that there will be horizontal gap between the canvas & boundary.

**Comment by RadhikaMalpani1702** [comment]
Hey @singodiyashubham87 

Done the changes

image

image

**Comment by RadhikaMalpani1702** [comment]
@singodiyashubham87 Please merge this PR

**Comment by RadhikaMalpani1702** [comment]
Hey @singodiyashubham87  I have resolved this conflicts please merge this PR

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
