### PR TITLE
Fixed the button

### PR DESCRIPTION
**Pull request by ayush-848**
# Issue Title: Text change in the last tutorial card
*resolve issue:* #158 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️
I have checked the deployment in my localhost server

Describe how have you verified the changes made.
image

### CODE REVIEW

**Comment by ayush-848** [comment]
@singodiyashubham87 please check the PR

**Review by soumya-maheshwari — APPROVED** [review]
LGTM 
Good to go

**Comment by ayush-848** [comment]
@soumya-maheshwari if everything is good to go then please merge this PR

**Comment by ayush-848** [comment]
@singodiyashubham87 please check my PR and if everything is great please merge it.

**Comment by ayush-848** [comment]
@singodiyashubham87 I mentioned the Issue no and title in the template now. 
Please have a look.

**Comment by singodiyashubham87** [comment]
@ayush-848 Thanks for contributing, Keep it up :)

**Comment by ayush-848** [comment]
Hello @singodiyashubham87 please add label to this merge. The points of  this is not given in the leaderboard

**Comment by ayush-848** [comment]
@0xabdulkhalid please add level label to this PR

**Pull request merged**
