### PR TITLE
Closes issue 43

### PR DESCRIPTION
**Pull request by Leorasaharia**
**Issue Title: Chatbot for the web-app #43 
resolve issue: #43** 

**Type of change ☑️**
What sort of change have you made:

[ x] Bug fix (non-breaking change which fixes an issue)
[ x] New feature (non-breaking change which adds functionality) {added a new feature of chatbot}
[x ] Code style update (formatting, and styling of the chatbot)

**Checklist: ☑️**
[ x] My code follows the guidelines of this project.
[ x] I have performed a self-review of my own code.
[ x] I have commented my code, particularly wherever it was hard to understand.
[ x] My changes generate no new warnings.
[x ] I have added things that prove my fix is effective or that my feature works.
[ x] Any dependent changes have been merged and published in downstream modules.

**How Has This Been Tested? ⚙️**
_
Screenshot (4776)
Screenshot (4775)
Screenshot (4774)
Screenshot (4773)
Screenshot (4777)_

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Leorasaharia I must say, You did a great work, I've reviewed the PR & here are some changes: 

- Make the theme of the drawbot relevant to the webapp theme(greyish type) & not pinkish & blue themed.
- Add a good avatar, If you want I can send you, just drop me a message on discord.
image

**Comment by Leorasaharia** [comment]
Ok, I will do that.

**Review by singodiyashubham87 — CHANGES_REQUESTED** [review]
Remove this chatbot.jpg file and use the web app logo instead.

**Comment by Leorasaharia** [comment]
changes were completed as requested @singodiyashubham87

**Pull request closed without merging**
