### PR TITLE
Issue#332: Disabled text-selection.

### PR DESCRIPTION
**Pull request by SahilThakur02**
This PR implements text selection disabling for React components or the entire webpage. This protects sensitive content and enhances user experience.

# Issue Title: [FEAT] Disable text selection on website.
*resolve issue:* #332

## Type of change ☑️

What sort of change have you made:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.
**Have tested the changes locally.**

### CODE REVIEW

**Comment by SahilThakur02** [comment]
@singodiyashubham87 please review

**Comment by singodiyashubham87** [comment]
@SahilThakur02 I've already added my review, Make the reviewed changes.

**Comment by SahilThakur02** [comment]
> @SahilThakur02 I've already added my review, Make the reviewed changes.

@singodiyashubham87 can't see the review, please give me some leads, I am very new to contributions and PR.

**Comment by singodiyashubham87** [comment]
@SahilThakur02 
image

**Comment by SahilThakur02** [comment]
@singodiyashubham87 made changes as suggested, please check

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@SahilThakur02 Well Done, Keep contributing :)

**Comment by SahilThakur02** [comment]
@singodiyashubham87 Please label it with a level, wont get points otherwise.

**Pull request merged**
