### PR TITLE
Adding aspect ratio feature

### PR DESCRIPTION
**Pull request by Jasleen1210**
# Issue Title: 
*closes* #333 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Resolve conflicts.

**Comment by Jasleen1210** [comment]
@singodiyashubham87 Done

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Pull the latest changes.

**Comment by Jasleen1210** [comment]
Done! sorry for the delay @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Conflicts!

**Comment by Jasleen1210** [comment]
@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Still conflicts.

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Your code still has errors, consider creating a new PR.
image

**Pull request closed without merging**
