### PR TITLE
added more colors, amde the drawboard more responsive for small devices, added chatbot folder

### PR DESCRIPTION
**Pull request by Leorasaharia**
# Issue Title: 
*resolve issue:* #43

## Type of change ☑️

What sort of change have you made:
<!--
Example how to mark a checkbox:-
- My code follows the code style of this project.
- [yes ] Bug fix (non-breaking change which fixes an issue) (responsiveness of board)
- [ yes] New feature (non-breaking change which adds functionality) (added more colors) (created a chatbot folder)
- [ yes] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist: ☑️
<!--
Example how to mark a checkbox:-
- [yes] My code follows the code style of this project.
- [yes ] My code follows the guidelines of this project.
- [yes ] I have performed a self-review of my own code.
- [ yes] I have commented my code, particularly wherever it was hard to understand. (chatbot folder files)
- [ yes] I have made corresponding changes to the documentation. (file updates - helper.js, canvas.js)
- [yes ] My changes generate no new warnings.
- [ yes] I have added things that prove my fix is effective or that my feature works.

 
## How Has This Been Tested? ⚙️
I observed that the drawing board was not sufficiently responsive when attempting to zoom out of the page or split the screen. Consequently, I focused on enhancing its responsiveness by implementing adjustments. Additionally, I expanded the color palette by adding more options in the helpers.js file.

Furthermore, I organized the Chatbot component into its own folder (chatbot) and separated its logic and styling into chatbot.jsx and chatbot.css, respectively. However, the implementation process is currently taking longer than anticipated.

To maintain project integrity and ensure a seamless integration, I've temporarily commented out the Chatbot folder's files and refrained from calling it within the app.jsx file. I aim to complete the implementation as soon as possible, prioritizing quality and efficiency.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Leorasaharia Kindly add working video.

**Comment by Leorasaharia** [comment]
https://github.com/singodiyashubham87/Draw-it-out/assets/143778430/7bcf06e0-090c-4c41-af05-f4a9858e0f2d

here's the video i recorded to show the responsiveness of the site and the color preferences but however did not implement the chatbot till now, it's still under progress.

**Comment by singodiyashubham87** [comment]
@Leorasaharia You were supposed to add a chatbot according to the issue, but you did everything else expect that. This PR can't be merged, Kindly add the chatbot and create a new PR for that only.

**Comment by Leorasaharia** [comment]
Sure sir that's in progress I'm sorry

**Comment by Leorasaharia** [comment]
It's taking time because I have to integrate an ML model into your project.
The complete implementation is taking time since it also requires setting
up a database and a dataset for it to work on. I admit I've completed
everything else except for the chatbot. However, when I started working on
your website, I noticed a minor issue with the drawing board, which is the
heart of the project. I prioritized making it responsive. I'm already
working on the chatbot implementation already mentioned earlier. Hope you
understand

**Comment by singodiyashubham87** [comment]
@Leorasaharia I highly encourage your efforts but a PR must contain only the relevant changes. Kindly don't resolve those responsiveness issues in this PR, This PR was just for the chatbot issue. There can be a separate issue for responsiveness and then you can work on that if already there is no issue raised by someone.

& Please create a new fresh PR, I guess mistakenly you have added all the commits.
image

**Pull request closed without merging**
