### PR TITLE
closes Issue #170

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
# Issue Title: 
Separating Shape buttons

*resolve issue:* #170

## Type of change ☑️

What sort of change have you made:
I have added dropdown for shapes

### CODE REVIEW

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
We don't need separate state for setting `imagePath`

Instead you can create an object which points to the images, For example:
```js
const imagePaths = {
  'rectangle': rectImg,
  'circle': circleImg,
  'triangle': triangleImg
}
```

You can utilize this object from `img` like,
```js
<img src={imagePaths[selectedTool]}/>
```

**Comment by 0xabdulkhalid** [comment]
Additionally, I would recommend you to follow guidelines for creating PR.

You need to properly name the `Issue Title` with actual Title, please don't leave it unchanged.

**Comment by AMISH-KHAN** [comment]
> Additionally, I would recommend you to follow guidelines for creating PR.
> 
> You need to properly name the `Issue Title` with actual Title, please don't leave it unchanged.

Sorry for that I have changed the Title and I will make sure not to change that in future.

**Comment by AMISH-KHAN** [comment]
> We don't need separate state for setting `imagePath`
> 
> Instead you can create an object which points to the images, For example:
> 
> ```js
> const imagePaths = {
>   'rectangle': rectImg,
>   'circle': circleImg,
>   'triangle': triangleImg
> }
> ```
> 
> You can utilize this object from `img` like,
> 
> ```js
> 
> ```

Sure I will do that but just for learning part.....what I did is it a bad practice??

**Comment by 0xabdulkhalid** [comment]
Yeah, using state for too much stuff is a bad practice. I agree that you're learning but you need to learn in a right way by following good practices.

Update the code as per my request, then tag me here in the comments.

**Comment by AMISH-KHAN** [comment]
@0xabdulkhalid  I have made the requested changes please check

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN You haven't merged the latest changes, kindly fix it.

# Actual One: 
image

# Yours One: 
image

**Comment by AMISH-KHAN** [comment]
hey I have just noticed that some one has made the dropdown what should I do


https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/321cbdcd-dd08-443b-b4dd-46c9e471fd62

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN Do one thing then reposition the toolbar to centre, they are not aligned.

I will add my changes if that's okay?

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN What you wanna add in your changes?

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Seems good, you can resolve all the conflicts & make a fresh PR, I'll merge it.

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Conflicts are still there, advised to create a fresh PR.

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Any updates?

**Comment by AMISH-KHAN** [comment]
Just give me a day or two I will do it soon

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Are you working on this?

**Comment by singodiyashubham87** [comment]
Closing due to inactivity.

**Pull request closed without merging**
