### PR TITLE
closes issue #166

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
# Issue Title:  Dark theme not working
*resolve issue:* #166 

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/75057b44-c0bd-4ed2-8918-a7ba503b2778

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

### CODE REVIEW

**Comment by AMISH-KHAN** [comment]
Well I did pull the main branch until then you didn't merge the changes. I will pull again and commit the changes ASAP.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 please review it again I made the requested changes

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Well Done! :)

**Pull request merged**
