### PR TITLE
Adding aspect ratio feature

### PR DESCRIPTION
**Pull request by Jasleen1210**
# Issue Title: 
*closes* #333 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

### CODE REVIEW

**Comment by Jasleen1210** [comment]
Im not sure why the checks keep failing, i've resolved all conflicts on my end and the code works fine on my pc, any advice as to what the error might be? @singodiyashubham87 ?

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Your code has errors, a **div** tag is misplaced, fix it.
image

**Comment by singodiyashubham87** [comment]
@Jasleen1210 I've tried changing the aspected ratio, but it's not changing, kindly check your side.

**Comment by Jasleen1210** [comment]
It appears that the latest changes i made were conflicting with the function, i've removed that code for now (im unable to find the reason for conflict)
Also fixed a minor hover issue i noticed


https://github.com/singodiyashubham87/Draw-it-out/assets/144164397/ee1a44c1-f528-446c-885e-18b1a98ad1ce

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Jasleen1210 You are advised not to use this type of non-contextual commit messages. 
image

**Pull request merged**
