### PR TITLE
fix(footer): Adjust chatbot icon alignment

### PR DESCRIPTION
**Pull request by DebapriyaJha**
# Issue Title:  fix Bug(footer): Adjust chatbot icon alignment
*resolve issue:* #253 

## Type of change ☑️
What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## How Has This Been Tested? ⚙️
The changes are tested locally by running the application and verifying the alignment of the chatbot and Gmail icons in the footer. Both icons are now visible and properly spaced out, resolving the overlap issue. Testing is also performed across different screen sizes and resolutions to ensure the fix works as expected.

Screenshots-
Before:
alignment

After:
align1

### CODE REVIEW

**Comment by DebapriyaJha** [comment]
@singodiyashubham87 Please have a look at my PR and merge it.

**Comment by singodiyashubham87** [comment]
@DebapriyaJha Neither you have to change the **package.json && package-lock.json** files nor you are advised to write **custom CSS**, Use **TailwindCSS** classes for styling.

**Comment by DebapriyaJha** [comment]
okay i will make the changes

**Comment by singodiyashubham87** [comment]
@DebapriyaJha Any updates?

**Comment by DebapriyaJha** [comment]
Yes I am working on it will complete and try to submit my PR in 2 days

**Pull request closed without merging**
