### PR TITLE
feat(navbar): Added a hover feature on guidelines icon

### PR DESCRIPTION
**Pull request by payalgupta25**
# Issue Title:  
<h3>feat(navbar): Added a hover feature on guidelines icon</h3>

The issue was that on hovering on the guidelines icon, it was not displaying the word guideline so that the user may get to know what the icon actually means

*resolved issue:* #258

## Type of change ☑️

I have added a feature in which on hovering on the guidelines icon it displays guidelines

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Before
image

After (On Hover)
image

Describe how have you verified the changes made.

I have verified the changes made by me by running the website after changing the code and I have attached the screenshots as well

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@payalgupta25 You don't need to add a span for this, Add the **title** attribute in the icon SVG, & that's it.

**Comment by payalgupta25** [comment]
> @payalgupta25 You don't need to add a span for this, Add the **title** attribute in the icon SVG, & that's it.

So do I need to change it now or you are gonna merge it this way only?

**Comment by singodiyashubham87** [comment]
@payalgupta25 You have to change it & remove the span element.

**Comment by singodiyashubham87** [comment]
@payalgupta25 Any updates?

**Comment by singodiyashubham87** [comment]
Closing due to inactivity.

**Pull request closed without merging**
