### PR TITLE
Resolved Dark mode toggle

### PR DESCRIPTION
**Pull request by aslams2020**
Hi @singodiyashubham87,
## Issue Title: [BUG]🐞 Dark mode gets reset on refreshing the page
*resolve issue:* #289 

I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.

**Changes Made** :
- Save the dark mode preference to localStorage whenever it changes.
- Retrieve the dark mode preference from localStorage when the component mounts.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
 
## How Has This Been Tested? ⚙️ 
**Yes**

Please take a look and review it.

### CODE REVIEW

**Comment by aslams2020** [comment]
Hi, @singodiyashubham87 
Could you please review and merge it?

**Comment by singodiyashubham87** [comment]
@aslams2020 Merge main & push commit.

**Comment by aslams2020** [comment]
@singodiyashubham87 done.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
