### PR TITLE
Added a Walk Through

### PR DESCRIPTION
**Pull request by Rahulsingh1939**
# Issue Title: 
[FEAT] Add a animated Onboarding tour of website. #101

Added a Quick Walkthrough to our website using react-royride

## Type of change ☑️
Feature
drawIt

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Rahulsingh1939 Kindly resolve the merge conflicts.

**Comment by Rahulsingh1939** [comment]
Merge conflicts have been resolved, please check @singodiyashubham87.

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👍🏻

**Comment by 0xabdulkhalid** [comment]
Thank you for your Contribution @Rahulsingh1939 ✨

**Pull request merged**
