### PR TITLE
Added minor transition effect.

### PR DESCRIPTION
**Pull request by vishanurag**
## Issue Title: _Want to add a simple transition effect in the project._
*closes* #473 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

- I have tested my changes via running it on my local system.

https://github.com/user-attachments/assets/66bbf259-fb5d-468f-832c-40c6c3211438

<hr>

_Please review and merge my pull-request under GSSoC'24_

### CODE REVIEW

**Comment by vishanurag** [comment]
@singodiyashubham87 Please review my pull-request and let me know that everything is fine or not.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@vishanurag Well Done! :)

**Comment by vishanurag** [comment]
@singodiyashubham87 sir I think you forgot to assign this pr to me. Please assign this pr to me 🙏

**Pull request merged**
