### PR TITLE
Logo 

### PR DESCRIPTION
**Pull request by hritika2409**
Issue Title: LOGO FOR
 WEBSITE
resolve issue: #81

Type of change ☑️

Added the 2 copies of the logo which i made with there appropriate names.

Checklist: ☑️

- [x]  My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [x]  I have added things that prove my fix is effective or that my feature works.
- [x]  Any dependent changes have been merged and published in downstream modules.

How Has This Been Tested? ⚙️
Describe how have you verified the changes made.

-If u really like the changes please do merge it.I will be really very thankful and grateful to you

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@hritika2409 You have to put both these images under **src/assets/images**

**Comment by hritika2409** [comment]
@singodiyashubham87 Added the 2 copies of the logo which i made with there appropriate names.

**Comment by singodiyashubham87** [comment]
@hritika2409 I know you have added the logo images but you have to add them in the images folder which is there under **src/assets/images**.

**Comment by hritika2409** [comment]
@singodiyashubham87 done & i m really very sorry,as you have to explain alot in this process but thank you so much for your guidance.

**Comment by singodiyashubham87** [comment]
@hritika2409 Now you removed the curly brace from the CSS file which is causing an error in deployment, kindly fix it & I'll advise you to create a new fresh PR, we can't have more than 6 commits, Try to understand.

image

**Pull request closed without merging**
