### PR TITLE
Added logo

### PR DESCRIPTION
**Pull request by hritika2409**
# Issue Title: LOGO FOR 

- [x] WEBSITE

*resolve issue:* #issue_number  #81

## Type of change ☑️

What sort of change have you made:

Group 1

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

-I have not placed that in the main website as if you need any change you can tell me,i have added the file in your list as group1 png and even added the image with this message.So if you need anychange please do let me know-

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@hritika2409 There is no need of the app name in the logo, just make it appealing and according to the color theme of the webapp.

**Comment by hritika2409** [comment]
Group 1 (3)
 I have changed the complete logo .Is it fine .Now i made it as simple as possible and even according to the website

**Comment by singodiyashubham87** [comment]
@hritika2409 Don't you think this all black svg will not be visible in the webapp's logo?
Maybe you should add circle white BG or something to make it visible clearly.

**Comment by hritika2409** [comment]
@singodiyashubham87 Ok i can do that but is this the final one,like i just have to add a circle with white background or you need anyother changes?

**Comment by hritika2409** [comment]
@singodiyashubham87 I have made the changes as you asked but rather than white i changed it to grey according to the website
1)The changed version:
Group 3

@)If its not that visible as its background is transparent so that it can fit,it will actually look like this ,when applied:
Screenshot 2024-05-27 225047

**Comment by hritika2409** [comment]
@singodiyashubham87 Or should i remove the outline of the circle
Screenshot 2024-05-27 225318

**Comment by singodiyashubham87** [comment]
@hritika2409 Remove the outline and also make it png(transparent bg & not white), we just wanted the circle part to be visible which is there in the logo you created.

**Comment by singodiyashubham87** [comment]
@hritika2409 One more thing, Do remember to pull the latest changes & make your repo sync with the latest code then push o/w it will create conflicts.

**Comment by hritika2409** [comment]
I have made the changes but everytime i tried to change the code the preview site is blank
Screenshot 2024-05-29 223105

**Comment by singodiyashubham87** [comment]
@hritika2409 Maybe you are confused in something, You don't have to change the code, you just have to add two copies of the logo image with the appropriate names (webLogo.png & readmeLogo.png)

**Pull request closed without merging**
