### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by Skb08**
# Issue Title: Making the website responsive
# Issue No: #152

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Video:

https://github.com/singodiyashubham87/Draw-it-out/assets/113046759/c989dc40-53e0-4f39-8f51-c0c2a6d519a9

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Skb08 Issue title is not equal to issue number.

**Comment by Skb08** [comment]
By mistake I changed package-lock.json, after that,I undo the change
and you assign me in this issue #152 
Screenshot (154)

**Comment by Skb08** [comment]
updated video:

https://github.com/singodiyashubham87/Draw-it-out/assets/113046759/6a62e7c5-350c-49b8-a809-6acc11aa4e27

**Comment by singodiyashubham87** [comment]
@Skb08 In the title of the PR you are supposed to write a descriptive title & not the issue number.

**Comment by singodiyashubham87** [comment]
@Skb08 Make the canvas size 90% of screen width on small devices, don't let it touch the corners.

**Comment by Skb08** [comment]
@singodiyashubham87 Now it's fine i think

**Comment by singodiyashubham87** [comment]
@Skb08 On small screens the layout is still breaking.
image


Secondly, your PR still has the package-lock.json changes that you made.

**Comment by Skb08** [comment]
MB-1

**Comment by singodiyashubham87** [comment]
@Skb08 Both files are still modified
image

**Comment by Skb08** [comment]
@singodiyashubham87  Sorry, for that it was due to missing a single line

**Comment by singodiyashubham87** [comment]
@Skb08 Now you removed every change except package.json & package-lock.json
image

**Comment by Skb08** [comment]
@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Skb08 The canvas size increase/decrease functionality is not working in your changes, fix it.

**Comment by Skb08** [comment]
@singodiyashubham87 fixed the canvas size increase/decrease funcationality

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Skb08 Well done, keep contributing :)

**Pull request merged**
