### PR TITLE
feat: Add eye button to hide and show menu and bgcolor

### PR DESCRIPTION
**Pull request by shivamb11**
# Issue Title: [FEAT] Option to Hide the buttons and bg choices
*resolve issue:* #38 

## Type of change ☑️

Added an eye button, toggling which can hide or show the menu and bgcolors. (Default show).
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

I verified them on my own visually.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@shivamb11 Well Done, there is one suggestion from my side, decrease the size of the eye button & add two separate eye buttons, one for drawing tools and the other one for background color.

image

**Comment by shivamb11** [comment]
@singodiyashubham87 Where should I place them, do you have something in mind ?

**Comment by singodiyashubham87** [comment]
@shivamb11 Just decrease the size of icon a little and push the code again, no need of adding separate eye buttons.

**Comment by shivamb11** [comment]
@singodiyashubham87 I have done as said. Please check.,

**Review by singodiyashubham87 — APPROVED** [review]
LGTM!

**Pull request merged**
