### PR TITLE
Added responsiveness to Menu bar

### LINKED ISSUE #169: [BUG] Unresponsive Menu Component
**Describe the bug**
Currently the Menu component behaves not as expected, with window resize.

**To Reproduce**
1. Go to website
2. Resize the page
3. Notice the menu bar

**Expected behavior**
Menu component should adapt to the screen size and should not break its child nodes alignment.
This could be done by fixing the styling for the adjacent eye & theme button. And adding reponsiveness to the Menu component! 

**Screenshots**
first
second

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]

Hey @singodiyashubham87, I would like to work on this to for GSSoC'24. This would improve the User Experience and make application look better and easy to use.

### PR DESCRIPTION
**Pull request by The-Phoenics**
# Issue Title: Responsive Menu *toolbar*
Fixes #169 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
### Screenshots
**Full screen size**
fullscreen

**Medium screen size**
mediumside

**Small screen size**
smallersize

### CODE REVIEW

**Comment by The-Phoenics** [comment]
Hey @singodiyashubham87, 
I've changed the styling for the Menu (toolbar) component and adjusted the division with the theme and coffee button to the right, as you can see in the attached screenshots.

- The current layout will break as the Background component has not been properly adjusted to fit in the layout. Respective styling is needed for the Background panel.

Can you review the PR?

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
The layout issue need to be fixed,

https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/da982534-6e00-4c79-8faf-a15837f8034f

**Comment by The-Phoenics** [comment]
> The layout issue need to be fixed,
> 
> https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/da982534-6e00-4c79-8faf-a15837f8034f
> 
> 

I'm aware of the layout breaking which is due to the styling of "BgColorChanger" Component.

And I think it would be a good idea to fix it in a separate issue with a separate PR, as this PR and it's corresponding issue is only concerned with "top toolbar".

**Comment by 0xabdulkhalid** [comment]
I agree with you @The-Phoenics, Now you need to resolve the conflicts so that PA can merge your PR.

**Comment by The-Phoenics** [comment]
Hey @0xabdulkhalid,
I have resolved the merge conflicts. Can you review it again?

**Comment by 0xabdulkhalid** [comment]
@The-Phoenics can you remove the arrows from these two buttons? Because it looks worse

image

And, you need to change this one to image, Just change it as a button just like other ones and you can change it's bg while it's toggled. (Convert checkbox into button).

**Comment by The-Phoenics** [comment]
Hey @0xabdulkhalid,
I've made necessary changes also add this new react icon indicating whether fill mode is selected.
fill-button-change
Can you review it again :)

**Comment by 0xabdulkhalid** [comment]
@The-Phoenics, there's a small issue with image button.

Currently the dropdown is shown while hovered, this feature not works on Mobile devices. It feels buggy on Desktop though

https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/e38ae9db-8239-4def-8b13-d3079e70650a

The dropdown function is not properly implemented, you need to remove the below highlighted lines and want to implement `const toggleDropdown = () => setIsOpen(!isOpen)`.

```diff
<button
-  id="dropdownHoverButton"
-  data-dropdown-toggle="dropdownHover"
-  data-dropdown-trigger="hover"
   className="text-gray-700 bg-[#B7BABF] focus:ring-4 font-medium rounded-lg text-lg px-5 py-2.5 text-center inline-flex items-center   transform transition duration-300 ease-in-out "
   type="button"
-  onMouseEnter={handleMouseEnter}
-  onMouseLeave={handleMouseLeave}
+  onClick={toggleDropdown}
...
</button>

<div
-  id="dropdownHover"
-  onMouseEnter={handleMouseEnter}
-  onMouseLeave={handleMouseLeave}
```
You can just use `onClick` to set state, so that we can access dropdown without hassle.

After this change we can merge your PR with `level2` label, it deserves though!

**Comment by The-Phoenics** [comment]
Hey @0xabdulkhalid!
Done with the requested changes. I've also added that drop down arraw to rotate on toggle. Can you review it again?

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
Oops, @The-Phoenics! 😬

https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/75610b5a-4be6-444f-ab2b-329d850f241b

Both of the dropdowns are sharing same toggle function, you need to create a new toggle for Brush.

For example:

```js
const toggleSave = () => {
  setIsOpen(!isOpen);
};

const toggleBrush = () => {
  setIsDropdownOpen(!isDropdownOpen);
};
```

**Comment by The-Phoenics** [comment]
Can you review it again @0xabdulkhalid?

**Comment by singodiyashubham87** [comment]
@The-Phoenics You have done a good amount of work, kindly resolve the conflict so that I can merge the PR.

**Comment by The-Phoenics** [comment]
Hey @singodiyashubham87,
Can you check if  the conflicts have been resolved properly?

**Comment by singodiyashubham87** [comment]
@The-Phoenics Why is the tools container so different in yours?
Kindly fix it.

# Actual: 
image

# Yours: 
image

**Comment by The-Phoenics** [comment]
The intention behind the modification was to make the toolbar slightly smaller to properly fit the layout, as I proposed in #169 (https://github.com/singodiyashubham87/Draw-it-out/issues/169#issuecomment-2123779152) to make it an icon only toolbar. With some recommendations from @0xabdulkhalid, I adjusted its appearance accordingly. Please let me know if any further improvements are needed @singodiyashubham87.

**Comment by 0xabdulkhalid** [comment]
@singodiyashubham87, The actual Menu consists components in an inconsistent way. Every sub-component of Menu is not properly structured as per UI design, each of them looks different and works different though.

For example: The fill color option is a checkbox, which not at all styled. The shape selecting process also be difficult because there's no indicator of what we selected. The bottom captions for two of options, etc.

The inconsistency causes responsive issues, we can't make the Menu responsive until we design every element in a consistent way.

So that we wish to change it, During the process @The-Phoenics also resolved some existing bugs present on utilities of Menu.

**Comment by singodiyashubham87** [comment]
@0xabdulkhalid Okay, thanks for the clarification.
@The-Phoenics Well Done, Keep contributing :)

**Pull request merged**
