### PR TITLE
Updated Rate Us Page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Rate Us Page - Solved #385 
Kindly Please go through this PR @singodiyashubham87 

https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/a300a83e-67b5-47f3-aa4a-56984d25d187

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@sailaja-adapa On clicking the submit button, nothing is happening in the application. It should show some kind of toast like, response recorded or something for better UX.

**Comment by sailaja-adapa** [comment]
Yeah okk I'll add toastify message

**Comment by sailaja-adapa** [comment]
@singodiyashubham87 Go through this PR 


https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/414cddb5-24b2-4207-9d77-07e0ced4999c

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Well Done, Keep contributing :)

**Comment by sailaja-adapa** [comment]
Thank you ☺️ @singodiyashubham87

**Comment by sailaja-adapa** [comment]
Please add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
Please add level label under GSSOC'24 @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Sorry for the inconvenience, I've added the labels now :)

**Comment by sailaja-adapa** [comment]
Thank you ☺️ but you should also assign me this then only score will be updated in leaderboard

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Don't worry, you will get your points, you don't have to be assigned the PR for the backend to count your score, just wait for 12 hours & after that if the points are not reflected on the leaderboard, then ping me.

**Comment by sailaja-adapa** [comment]
Yeah okk Thank you @singodiyashubham87 :)

**Pull request merged**
