### PR TITLE
[DOCS] Addition of no of forks star issue closed open pr to readme.md

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Issue Title: 
*resolve issue:* #249 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Added Code

```
<table align="center">
    <thead align="center">
        <tr border: 1px;>
            <td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Star.png" width="20" height="20"> Stars</b></td>
            <td><b>🍴 Forks</b></td>
            <td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Lady%20Beetle.png" width="20" height="20"> Issues</b></td>
            <td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Check%20Mark%20Button.png" width="20" height="20"> Open PRs</b></td>
            <td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Cross%20Mark.png" width="20" height="20"> Closed PRs</b></td>
        </tr>
     </thead>
    <tbody>
         <tr>
            <td><img alt="Stars" src="https://img.shields.io/github/stars/singodiyashubham87/Draw-it-out?style=flat&logo=github"/></td>
             <td><img alt="Forks" src="https://img.shields.io/github/forks/singodiyashubham87/Draw-it-out?style=flat&logo=github"/></td>
            <td><img alt="Issues" src="https://img.shields.io/github/issues/singodiyashubham87/Draw-it-out?style=flat&logo=github"/></td>
            <td><img alt="Open Pull Requests" src="https://img.shields.io/github/issues-pr/singodiyashubham87/Draw-it-out?style=flat&logo=github"/></td>
           <td><img alt="Closed Pull Requests" src="https://img.shields.io/github/issues-pr-closed/singodiyashubham87/Draw-it-out?style=flat&color=critical&logo=github"/></td>
        </tr>
    </tbody>
</table>

```

## Screenshoot of Changes

image

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 please review the Changes.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Anjaliavv51 Well Done, Keep contributing :)

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 please add Level label

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 please add level lavels

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 please add level lavels

**Comment by singodiyashubham87** [comment]
@Anjaliavv51 According to the gssoc rules, this PR deserves only the gssoc label because it's a README change.

**Pull request merged**
