### PR TITLE
Enhance footer interactivity with hover effect

### PR DESCRIPTION
**Pull request by vidipsingh**
# Issue Title: Footer hover effects improvement
*closes* #447 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

**1. Visual Testing:**

- Thoroughly examined the footer element in your browser.
- Hovered over the footer and observed if the desired hover effect occurs
- Tested across various devices and browsers to ensure consistency.

### CODE REVIEW

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
### Hi there @vidipsingh 👋🏻

You'll need to add `transition-all` utility class for all `a` elements in order to support smoother transitions. Because without declaring it the Hover effects looks bad. You can tweak the transition duration too with `duration` class like `duration-300` for `3` milliseconds.

Additionally, I would recommend you to create a new component for `a` because you've just re-written it many times. You can name it as `FooterLink.jsx` or whatever you wish.

Eg: 
```js
export default function FooterLink({link, label, children}) {
  return (
    <a href={link || "#"} className="text-white flex items-center transition-all duration-300 hover:text-gray-200 hover:rounded-sm hover:scale-110">
      {children}
      <span className="ml-2">{label}</span>
    </a>
  )
}
```

We can use this like,
```js
<FooterLink label={"Home"}>
  <AiFillHome className="h-6 w-6" />
</FooterLink>
```

Notify me once you have made the changes!

**Comment by 0xabdulkhalid** [comment]
Oops, @vidipsingh! You're still not assigned to this issue #447. You can't create PR for an Issue rised by another Contributor.

@singodiyashubham87, What we can do for now? Cause @aanchalpahuja18 have not responded on Issue yet.

Admin needs to take the Decision.

**Comment by aanchalpahuja18** [comment]
@0xabdulkhalid I want to solve the issue sir & I am still interested to do so kindly assign me the issue

**Comment by vidipsingh** [comment]
Hi @0xabdulkhalid ,

Since no one was previously assigned this issue, I went ahead and made the required changes.  Should I make the said changes?

If @aanchalpahuja18  would prefer to work on this issue, you can just close my PR.  Let me know if my changes look good to you.

**Comment by 0xabdulkhalid** [comment]
As per GSSoC Guidelines, Issues will only be assigned in FCFS Basis.
So @aanchalpahuja18 is the one Who created that Issue, If that's the case then they should be assigned first.

@vidipsingh you don't need to resolve the changes as per my request, I'm closing PR. Let @aanchalpahuja18 work on this Issue.

Thank you @vidipsingh for your contribution, You can work on any new Issues.

**Pull request closed without merging**
