### PR TITLE
added chatbot

### PR DESCRIPTION
**Pull request by Leorasaharia**
# Issue Title: Chatbot for the web-app #43
*resolve issue:* #43 

## Type of change ☑️

What sort of change have you made:

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality) {added a new feature of chatbot}
- [x ] Code style update (formatting, and styling of the chatbot)

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.
- [x ] I have added things that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

This chatbot, named Drawbot, engages users in a conversation about their drawing preferences. It starts by greeting the user and asking what they plan to draw today. After the user responds, the chatbot asks if they would like suggestions on what to draw. If the user chooses "Yes," the chatbot provides a list of drawing options. If the user selects "No," the conversation ends with a wish for good luck with their drawing. Additionally, there's an option to end the chat at any point with a button provided after the final message. 

https://github.com/singodiyashubham87/Draw-it-out/assets/143778430/e1763808-e45d-4b18-8a38-f565db0ece8e

### CODE REVIEW

**Comment by Leorasaharia** [comment]
honestly @singodiyashubham87 idk when i create a new request idk why all the commits tied up together is it because i do it from the main branch? i made a new branch too but committing to the new branch was not possible idk why it had many conflicts.

**Comment by singodiyashubham87** [comment]
@Leorasaharia Do one thing, sync your forked repo then pull the main branch to your local system and then resolve the conflicts and the create a PR from a new branch.

**Comment by singodiyashubham87** [comment]
@Leorasaharia If you still face issue, then you can contact me  or mentor @0xabdulkhalid on discord, we will help you out.

**Comment by Leorasaharia** [comment]
Okay got it, will do it

**Pull request closed without merging**
