### PR TITLE
Added "Cursor Trail Effect" To Look More Artistic

### LINKED ISSUE #443: Feature Addition: Add Cursor Trail Effect To Look More Artistic
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @singodiyashubham87 

I would like to enhance the user experience on the "Draw it Out" website by adding an artistic **trail effect to the cursor**. This feature will make the website more engaging and visually appealing, aligning with its theme of canvas drawing.

I will make sure:
- It is smooth without lag.
- Aesthetically pleasing
- The trail effect does not interfere with other interactive elements on the page.
- It does not irritate to users instead it will be fun to play with!

Like This:

https://github.com/singodiyashubham87/Draw-it-out/assets/101971980/97bbc57e-3051-492f-89fe-2717a41a64a0

### Use Case

- The trail effect will provide a more interactive and artistic feel to the cursor, which fits the creative nature of the "Draw it Out" website.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
# Issue Title: Add Cursor Trail Effect To Look More Artistic 

Hey @singodiyashubham87 

I have added the cursor trail effect to the website

 -  closes #443 
 
### **Changes I made:**

- Created Trail effect, The CSS and HTML files have been updated to support this change in `index.html`
- The color gradient for trail effect are `#484c4c` and `#b0d5fb`, creating a visually appealing effect. 
- The **Trail effect** smoothly **synchronizes** with the cursor movement.
          - The `mousemove` event listener adjusts for the vertical scroll position using `window.scrollY.`
          - The circles' positions are updated in the `animateCircles` function, ensuring they follow the cursor with a trailing effect.
- It works fast and smoothly and feels light-weight

And the most important it does not hinder any part of the website or drawing components, it works smoothly with them without causing any lag or drawing issues

(The trail looks great and suits the website, that's why I did not hide it on the canvas!)

### Screen Record 

https://github.com/singodiyashubham87/Draw-it-out/assets/101971980/fea5872a-9eb3-4c0c-9780-42235bd60efb

(The video is not fast-paced, the speed of the video is normal, the trail effect works smoothly without any lag)

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 Please take a look and review it.
 Also, I have one request, if possible could you **please increase the level for this PR** as per the changes I have made? I'll appreciate it. If you need any changes, pls do tell me, Thank you!

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@MastanSayyad This is not how we structure a React project, you don't have to change the index.html file, instead create a separate react component for the cursor tail & then import that component in App, secondly don't use internal CSS, the project uses TailwindCSS, kindly follow the project guidelines.

**Comment by MastanSayyad** [comment]
Hey @singodiyashubham87 The trail effect is not working correctly if we creat a trail component, the way I have done created earlier is the most convenient way for the cursor trail effect to work smoothly

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
The changes you proposed does not match to our contributing guidelines, You not allowed to write Vanilla JS & CSS.

Instead you can try out packages like [react-animated-cursor](https://www.npmjs.com/package/react-animated-cursor) to implement cursor effects on our React based Application.

You can find more packages like it, You can use any package for adding Trailing Cursor Effect.

Make sure to tag Me (@0xabdulkhalid, Mentor) or Project Admin (@singodiyashubham87) once you have done the requested changes.

Thank You!

**Comment by MastanSayyad** [comment]
Got it, thank you for letting me know! @0xabdulkhalid

**Comment by MastanSayyad** [comment]
Hey @singodiyashubham87 and @0xabdulkhalid 

I have made the changes and ensured to follow the contributing guidelines of the project
also, I have tried drawing and it does not hinder any part of the drawing components and works smoothly


https://github.com/singodiyashubham87/Draw-it-out/assets/101971980/f4b01006-3526-49e1-9177-8304bdb60768

please take a look and review it!

**Comment by MastanSayyad** [comment]
@0xabdulkhalid please take a look and review it!

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👀

**Comment by MastanSayyad** [comment]
@singodiyashubham87 please review it!

**Comment by singodiyashubham87** [comment]
@MastanSayyad Change the file name to "CursorTrail.jsx", Remember always to follow the convention of using Pascalcase for naming React components.

**Comment by MastanSayyad** [comment]
> @MastanSayyad Change the file name to "CursorTrail.jsx", Remember always to follow the convention of using Pascalcase for naming React components.

@singodiyashubham87 Got it! thank you for letting me know, I will make the chnages right away

**Comment by singodiyashubham87** [comment]
@MastanSayyad You have just changed the name of the import, you also have to rename the actual component.

**Comment by MastanSayyad** [comment]
> @MastanSayyad You have just changed the name of the import, you also have to rename the actual component.

Yes I did but in commit it did not appear 

image

**Comment by singodiyashubham87** [comment]
@MastanSayyad Probably your changes are not saved then, try again.

**Comment by MastanSayyad** [comment]
> @MastanSayyad Probably your changes are not saved then, try again.

Yes

**Comment by MastanSayyad** [comment]
@singodiyashubham87 This should work! extremely sorry for the inconvenience from my side

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
