### PR TITLE
Fix: Added the missing avatar in the chatbot section (#192)

### PR DESCRIPTION
**Pull request by Shubham-1068**
# Issue Title: 
*Resolve issue:* #192 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

I have tested it on my local server.

## Screenshots : 

Screenshot 2024-05-22 234906

### CODE REVIEW

**Comment by soumya-maheshwari** [comment]
Hey @Shubham-1068,

Could you kindly share a screenshot of the changes you've made? It's often beneficial to attach a screenshot along with the PR for better clarity.

**Comment by Shubham-1068** [comment]
As per your request i have added a screenshot to my PR, kindly review it.

**Comment by soumya-maheshwari** [comment]
LGTM

ready to be merged! @singodiyashubham87 🚀

**Review by soumya-maheshwari — APPROVED** [review]

**Review by singodiyashubham87 — CHANGES_REQUESTED** [review]
@Shubham-1068 As @soumya-maheshwari mentioned, kindly fix the issue.
The avatar is not visible on the development build.

**Comment by singodiyashubham87** [comment]
@Shubham-1068 Are you working on the issue?
Do reply asap o/w I have to close the PR & assign the issue to next person who asked to resolve the issue.

**Pull request closed without merging**
