### PR TITLE
cursor style changed

### PR DESCRIPTION
**Pull request by yasaswi-2204**
Hi @singodiyashubham87,

# Issue Title: Use of another cursor type
*resolve issue:* #199

## Type of change ☑️
I have updated the cursor style on the white board from crosshair to a pointer.

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️
Please take a look  and review it.
I have verified it

### CODE REVIEW

**Comment by yasaswi-2204** [comment]
Dear @singodiyashubham87,
Please review my PR and merge it.

Thankyou

**Review by singodiyashubham87 — APPROVED** [review]

**Comment by yasaswi-2204** [comment]
Thank you @singodiyashubham87, for believing in my expertise and assigning me this issue. As you said, Yeah! It is my first PR in Daw-it-out. Hoping many more to go....

**Comment by yasaswi-2204** [comment]
Dear PA,
Please assign thelevel number to my PR. So that my score will be added.
Thank you

**Comment by yasaswi-2204** [comment]
Dear @singodiyashubham87 ,
Please assign the level label to my PR
Thank you

**Comment by singodiyashubham87** [comment]
@yasaswi-2204 According to the rules set by the program managers, this PR deserves a gssoc label only.
So, I can't add level label.

**Pull request merged**
