### PR TITLE
[BUG] : Drawing screen Size fixed

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Issue Title: 
*resolve issue:* #132 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

[Screencast from 2024-05-16 13-55-10.webm](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/df719cab-304d-4b0e-b262-8ea7479d3915)

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@0xabdulkhalid  i will finished it.. please check

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👀

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Kindly resolve the conflicts.

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 kindly merge it..

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 There are again conflicts.

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 fix it.

**Comment by soumya-maheshwari** [comment]
@sivaprasath2004 
Kindly resolve the conflicts.

**Comment by sivaprasath2004** [comment]
@soumya-maheshwari  kindly last to first merge. if you merge first one my solution has been a conflict. so please last in first merge is a proper way.

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Your code changes contains errors, kindly fix them.

image

**Pull request closed without merging**
