### PR TITLE
alignment needs to done in multiple color section

### PR DESCRIPTION
**Pull request by kapilG0**
alignment needs to done in multiple color section

*resolve issue:* #194 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️
in mobile it is showing fine now 
image

Describe how have you verified the changes made.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@kapilG0 Push the latest changes & update the PR.

**Comment by kapilG0** [comment]
> @kapilG0 Push the latest changes & update the PR.

Do you mean I should take pull first and raise pr again ?

**Comment by singodiyashubham87** [comment]
@kapilG0 

# Your PR: 
image

# Actual: 
image

**Comment by kapilG0** [comment]
> @kapilG0
> 
> # Your PR:
> image
> 
> # Actual:
> image

Ok checking

**Comment by kapilG0** [comment]
> > @kapilG0
> > # Your PR:
> > image
> > # Actual:
> > image
> 
> Ok checking

Hello @singodiyashubham87 in my local it is showing in this way 
image
i think it is browser issue

**Comment by singodiyashubham87** [comment]
@kapilG0 Check in dark mode not light mode.

**Comment by kapilG0** [comment]
> @kapilG0 Check in dark mode not light mode.

hello thank you for this i have forgot to take pull from main i did that can you check now pls

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
