### PR TITLE
[Bug] : Responsive Fixes

### LINKED ISSUE #107: [BUG] ; Responsive Issue
**Describe the bug**
- In `Tab` and `mobile` screen doesn't proper Responsive

**To Reproduce**
1. Go to page
2. Click on inspect
3. Change to the screen size `400 to 900` 

**Expected behavior**
- All of the device can be perfect responsive but is not responsive.

## **Screenshots**
Screenshot from 2024-05-13 18-17-15

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device:Realme 8
 - OS: Android 12
 - Browser : chrome

### PR DESCRIPTION
**Pull request by sivaprasath2004**
#107 

## Type of change ☑️
- In this project was `Responsive` error fixes..
### Before
Screenshot from 2024-05-14 10-23-16

### After
Screenshot from 2024-05-14 10-22-42

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@0xabdulkhalid finished the issue please merge it...

**Comment by 0xabdulkhalid** [comment]
Hey @sivaprasath2004, please hang out for a moment. Project Admin want to make the PR Vercel deployment public so that Admins can verify it.

Thank you!

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Kindly resolve the conflicts.

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 kindly merge it..

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👍🏻

**Comment by 0xabdulkhalid** [comment]
Thank you for your Contribution! ❤️

**Pull request merged**
