### PR TITLE
Added "Import" button

### PR DESCRIPTION
**Pull request by StephenStolk**
# Issue Title: Adding "Import" button
*resolve issue:* #87 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Sample -

https://github.com/singodiyashubham87/Draw-it-out/assets/134587780/92fc7298-b4dd-46b2-afcf-5ee729eb50a9

Please check it.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@StephenStolk The importing is not working as expected, it's disturbing the whole canvas & app layout too. 
image

**Comment by StephenStolk** [comment]
I will fix the ui. 
Can you please tell the functionalities you are expecting ?
My fix can allow users-
- to import image,
- draw/color on the image

**Comment by singodiyashubham87** [comment]
@StephenStolk We want here a feature which will help the user to import any file & put it in canvas along with functionalities like dragging that image across the canvas & resizing.

**Comment by singodiyashubham87** [comment]
@StephenStolk Any updates?

**Comment by StephenStolk** [comment]
I will pull up the request by this weekend. I am working on fixing the ui

**Comment by singodiyashubham87** [comment]
@StephenStolk Is there any update?

**Comment by singodiyashubham87** [comment]
Closing due to inactivity.

**Pull request closed without merging**
