### PR TITLE
improved button accessability

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Issue Title: [Bug] Buttons are not Accessable
*resolve issue:* #47

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Tested using NVDIA Screen Reader Accessibility Device.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Kindly remove the changes you made to the package.json file.

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 sure

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 I will changed it.

**Review by singodiyashubham87 — APPROVED** [review]
LGTM!

**Pull request merged**
