### PR TITLE
closes issue #97

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
# Issue Title: 
*resolve issue:* #97 

## Type of change ☑️

I have added labels and change the styling of  icons so that it does not look bad

### CODE REVIEW

**Comment by AMISH-KHAN** [comment]
hey @singodiyashubham87 I would like to work on some more complex issues which will help in understanding the project more.
Moreover, I would also like to hear your vision about this project.

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Kindly resolve the conflicts, So that your PR can be merged.

**Review by singodiyashubham87 — CHANGES_REQUESTED** [review]
@AMISH-KHAN Kindly change "color" to "Color" and align the tools vertically centered.

image

**Comment by AMISH-KHAN** [comment]
Screenshot 2024-05-16 172525

@singodiyashubham87  I have made the requested changes please review it

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87  I have made the requested changes Please review it.

Screenshot 2024-05-16 173315

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Kindly resolve the conflicts.

**Comment by AMISH-KHAN** [comment]
Sure

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87  please review it

**Review by singodiyashubham87 — APPROVED** [review]

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Well Done, Keep Contributing :)

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN Well Done, Keep Contributing :)

Thanks Please assign me this #121

**Pull request merged**
