### PR TITLE
ADDED LOGO/IMAGE

### PR DESCRIPTION
**Pull request by Nih1tGupta**
BEAUTIFUL LOGO FOR YOUR WEBSITE

# Issue Title:  
*resolve issue:* #81 

## Type of change ☑️
ADDED A LOGO FOR WEBSITE
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [ ✅] My code follows the guidelines of this project.
- [ ✅] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [✅ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.
DRAWITFINAL

### CODE REVIEW

**Comment by Nih1tGupta** [comment]
Sir, Due to some issue, I was not able to add logo ,but createad one 
I have added source code for logo in your file,
Sorry for trouble , but if you think ,this is up to satisfaction, Please consider it
DRAWITFINAL

**Comment by Nih1tGupta** [comment]
Also  great thanks for assigning me this issue.

**Comment by Nih1tGupta** [comment]
LOGODRAW

**Comment by singodiyashubham87** [comment]
@Nih1tGupta I appreciate your efforts, but if the logo will be simple then It will be much more attractive as our applications theme is simple and clean.

**Comment by Nih1tGupta** [comment]
Logosimple
Link:
https://i.im.ge/2024/05/15/KM2Q4a.Logosimple.png

**Comment by singodiyashubham87** [comment]
@Nih1tGupta The logo is not looking appealing and cleaning.
& also resolve conflicts of your PR.

**Comment by singodiyashubham87** [comment]
@Nih1tGupta It's been 2 days since you haven't replied, So I'm closing the PR. Thanks for your efforts to contribute.

**Pull request closed without merging**
