### PR TITLE
Added Rate Us Page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Rate Us option - Solved #385 
Kindly Please go Through this PR @singodiyashubham87 

https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/28984db9-7d59-4336-8544-82f22176f1d7

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@singodiyashubham87 Please add Level Label Under GSSOC'24

**Comment by sailaja-adapa** [comment]
@singodiyashubham87 Kindly please go through this PR

**Comment by singodiyashubham87** [comment]
@sailaja-adapa I've already added my review yesterday, isn't it visible to you?
image

**Comment by sailaja-adapa** [comment]
I didn't seen these messages @singodiyashubham87 they are not visible to me

**Comment by sailaja-adapa** [comment]
IMG_20240703_072727

**Comment by sailaja-adapa** [comment]
I will change and update you soon @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Lemme look to the issue of the reviewed comment not being visible to you.

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Are the comments visible now?

**Comment by sailaja-adapa** [comment]
still no @singodiyashubham87 what might be the issue??

**Comment by singodiyashubham87** [comment]
@sailaja-adapa Even I'm also not sure what's the reason, but ignore it, I will write my comments from now on in simple discussion only.

**Comment by singodiyashubham87** [comment]
@sailaja-adapa The project uses tailwind classes for styling & not vanilla CSS. Kindly remove this styling & use tailwindcss classes for styling.

**Comment by sailaja-adapa** [comment]
Yeah okk @singodiyashubham87

**Comment by sailaja-adapa** [comment]
I will raise PR by this evening Thanks for your Patience ☺️

**Pull request closed without merging**
