### PR TITLE
404 not found fixed

### PR DESCRIPTION
**Pull request by ranjaniav1**
# Issue Title: Page not found 
*closes* #515

## Type of change ☑️

ii solve 404 page error
in footer click on contact then display contact same in team 

image
image
image
image

<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️
<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

in footer click on contact then display contact page as well as click on team then display team page :

### CODE REVIEW

**Comment by ranjaniav1** [comment]
@singodiyashubham87 ,can you tell me deploy the error in my local build sucess :
image

**Comment by ranjaniav1** [comment]
@singodiyashubham87 ,please merged it

**Comment by singodiyashubham87** [comment]
@Varsani2520 Your code has errors which in result is failing the vercel build, Kindly resolve them.

**Comment by ranjaniav1** [comment]
@singodiyashubham87 can you please give the screenshot of vercel deployment error

**Comment by ranjaniav1** [comment]
@singodiyashubham87 ,in my code no one is error see i try it build is sucess and deploy also sucess :
image
please merged it error automatically solved

**Comment by ranjaniav1** [comment]
@singodiyashubham87 please merged it

**Comment by ranjaniav1** [comment]
@singodiyashubham87 please merged it

**Pull request closed without merging**
