### PR TITLE
Added Footer with Social Media Icons

### PR DESCRIPTION
**Pull request by Asl2027**
# Issue Title: Add footer with social media icons
*resolve issue:* #62  

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.
-  I tested the footer by opening the web page in multiple browsers (Chrome and Edge) to ensure that the social media icons are displayed correctly and if they are redirecting properly to the social media.
- I verified that the hover effects on the social media icons work as expected.
- I checked the responsiveness of the footer to make sure it looks good on different screen sizes.
- I ensured there are no console errors or warnings during the testing.

https://github.com/singodiyashubham87/Draw-it-out/assets/150686467/ec8ce3a7-befe-43af-98f5-ce08d9451688

### CODE REVIEW

**Comment by soumya-maheshwari** [comment]
Hello @Asl2027 
This branch has conflicts
Resolve them

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]
Thank you for your contribution @Asl2027, in order to merge you PR you still need to make some improvements on layout in `footer`.

Preview

We can't place the social links on top of normal links. so you need to apply the following styles,

```css
.footercontainer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
}
```
You need to remove `margin` from `footerNav` and `width` from 'socialicons`

Then, you need to add `border-radius: 100%` for `.socialicons img` because during hover the icons like X and github are revealing their square shape. 

preview-2



Additionally you need to update the DOM order of elements,

```html
<div class="footercontainer">
   <div class="footerNav">....</div>
   <div class="socialicons">....</div>
</div>
```
We want to do this because of accessibility concerns, first we need to add links which are native to our Draw it out website then only we want to add social links.

Hope you understood the changes you need to do, please notify me once you done!

**Comment by singodiyashubham87** [comment]
@Asl2027 You must have read the README file first, It's clearly written that the tech-stack of the project is TailwindCSS, So you must do the styling part using TailwindCSS classes only and not custom CSS, kindly make the necessary changes which the mentors told you to do using TailwindCSS classes & not custom CSS.

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👀 

Now this PR is ready to be merged! @singodiyashubham87 🚀

**Comment by singodiyashubham87** [comment]
@Asl2027 Resolve the conflicts.

**Comment by Asl2027** [comment]
@singodiyashubham87 I have resolved the conflicts.

**Review by soumya-maheshwari — APPROVED** [review]
LGTM 

Now this PR is ready to be merged! @singodiyashubham87 🚀

**Review by singodiyashubham87 — CHANGES_REQUESTED** [review]
You have added logo of "X" multiple times, delete the one which is under the src directory.

**Comment by Asl2027** [comment]
> You have added logo of "X" multiple times, delete the one which is under the src directory.

I deleted the additional X.png.

**Comment by 0xabdulkhalid** [comment]
@Asl2027, Please wait for some time. Admin will merge it when he's online.

**Review by singodiyashubham87 — APPROVED** [review]

**Comment by singodiyashubham87** [comment]
@Asl2027 Well Done! Keep contributing :)

**Pull request merged**
