### PR TITLE
[BUG]: Pen Drawing not working after selecting Shapes #188

### PR DESCRIPTION
**Pull request by Prithwi32**
# Issue Title: [BUG]: Pen Drawing not working after selecting Shapes
*resolve issue:* #188 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Tested with localhost

### CODE REVIEW

**Comment by Prithwi32** [comment]
https://drive.google.com/file/d/138D52M1Wy5YrdO3fhZgrkrLVPsJL06qc/view?usp=sharing
@singodiyashubham87  check out PR and let me know feedback

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👀

**Comment by singodiyashubham87** [comment]
@Prithwi32 Resolve conflicts.

**Comment by Prithwi32** [comment]
@singodiyashubham87 check ot out now...resolved conflicts

**Comment by singodiyashubham87** [comment]
@Prithwi32 The "+" & "-" buttons are not working in your PR, fix them.

**Comment by Prithwi32** [comment]
> @Prithwi32 The "+" & "-" buttons are not working in your PR, fix them.

Yes..I fixed now, could u check now

**Comment by singodiyashubham87** [comment]
@Prithwi32 Well Done, Keep contributing :)

**Pull request merged**
