### PR TITLE
Update Footer.jsx

### PR DESCRIPTION
**Pull request by dishathakurata**
# Issue Title: Automatic copyright
*resolve issue:* #341 
Updated PR #349 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.
@singodiyashubham87 Please review this PR

### CODE REVIEW

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@dishathakurata Well Done, Keep contributing :)

**Comment by dishathakurata** [comment]
@singodiyashubham87 Thank you so much
Please add suitable level tag, otherwise my points won't be added.

**Comment by singodiyashubham87** [comment]
@dishathakurata According to the guidelines given to the PAs, we are not allowed to give any **level** labels to any PR which have a minute change like this one. Therefore **gssoc** is the only label, I can assign. It will be counted as **1 Point**.

**Comment by dishathakurata** [comment]
@singodiyashubham87 Okay, thank you

**Pull request merged**
