### PR TITLE
Add brush strokes

### PR DESCRIPTION
**Pull request by Harshitazz**
# Issue Title: Add brush strokes
*Add brush strokes:* #60

## Type of change ☑️

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update

## Checklist: ☑️

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- x[ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Harshitazz Your PR has conflicts, Do resolve them.

**Comment by singodiyashubham87** [comment]
@Harshitazz It'll be better if you can just make the border rounded and change the color of the container from pure white to greyish type that matches the theme of the application. 
image

**Comment by Harshitazz** [comment]
sure

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Harshitazz Kindly write meaningful commit messages, a commit message "push" doesn't really signifies anything.
image

**Pull request merged**
