### PR TITLE
[layout] - centered the canvas and adjusted side panel position

### PR DESCRIPTION
**Pull request by zaihl**
centered the canvas which was initially on the right side.
Screenshot 2024-06-01 112525

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@zaihl Which issue does this PR belongs to?

**Comment by zaihl** [comment]
> @zaihl Which issue does this PR belongs to?

https://github.com/singodiyashubham87/Draw-it-out/issues/246#issue-2328940391

**Comment by singodiyashubham87** [comment]
@zaihl You must follow the guidelines which clearly says that you have to create a PR only if you are assigned an issue.
You are not assigned issue #246 & still, you raised a PR, why?
This is not acceptable at all.
Closing the PR. You should wait until the issue gets assigned to you.

**Comment by zaihl** [comment]
> @zaihl You must follow the guidelines which clearly says that you have to create a PR only if you are assigned an issue.
> You are not assigned issue #246 & still, you raised a PR, why?
> This is not acceptable at all.
> Closing the PR. You should wait until the issue gets assigned to you.

I am sorry. I didn't keep that in mind. Forgive me as I am new to this.

**Comment by singodiyashubham87** [comment]
@zaihl It's okay for a beginner, do keep it in mind next time. I've assigned you the issue now & you can start working on it.

**Pull request closed without merging**
