### PR TITLE
rainbow background color"

### PR DESCRIPTION
**Pull request by siddxharth1**
# Issue Title: 
custom canvas background color picker
*resolve issue:* custom canvas background color picker #61

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@siddxharth1 Do add the issue number related to this PR.

**Comment by siddxharth1** [comment]
Added the name and the I'd of the issue 
custom canvas background color picker  #61

**Comment by singodiyashubham87** [comment]
@siddxharth1 I just told you to make it rainbow, you didn't have to change the position.
Kindly make the position same as previous one that is at top of other colors.

image

**Comment by siddxharth1** [comment]
Done can you please check

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
