### PR TITLE
[feat]:hover-on-color-icons

### PR DESCRIPTION
**Pull request by souvik-maity**
# Issue Title: Adding hover effect on color icons
*resolve issue:* #42

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.
Tested it manually on my local setup

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hi @souvik-maity 👋🏻 

Can you share us a screen-recorded video to see what changes you made?

**Comment by souvik-maity** [comment]
https://github.com/singodiyashubham87/Draw-it-out/assets/145227417/397fa435-90ff-4275-ab58-819c8037751f

**Comment by souvik-maity** [comment]
kindly check the changes made and consider merging it.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@souvik-maity Thanks for contributing! :)

**Pull request merged**
