### PR TITLE
feat: Export to PDF and SVG

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
# Issue Title: 
*resolve issue:* #34 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

I have used jsPdf library to export the canvas to PDF. 

https://github.com/singodiyashubham87/Draw-it-out/assets/91741581/c2ac3233-edac-49de-a6f7-8cef8b635089

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Vidip-Ghosh You PR is having conflicts & also the blur color of the Save as button is looking awkard and also the alignment of icons in the dropdown, add some gaps and make them align horizontally to acquire space.

**Comment by Vidip-Ghosh** [comment]
Screenshot 2024-05-12 at 10 22 21
@singodiyashubham87 I hope this button color is alright. Please let me know if any changes needs to be done.

**Comment by singodiyashubham87** [comment]
@Vidip-Ghosh Just add a little padding between the icons container and the icons & then we are good to go.

image

**Comment by Vidip-Ghosh** [comment]
@singodiyashubham87 now check.

**Comment by singodiyashubham87** [comment]
@Vidip-Ghosh Padding not in between the icons, rather between the icons and the icons-container

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh Padding not in between the icons, rather between the icons and the icons-container

Okay I'll look into it.

**Comment by singodiyashubham87** [comment]
@Vidip-Ghosh Kindly resolve the conflicts.

**Pull request merged**
