### PR TITLE
added preloader

### PR DESCRIPTION
**Pull request by Jagpreet153**
# Issue Title: Preloader
*resolve issue:* #265

## Type of change ☑️

What sort of change have you made: 
- [x] New feature (non-breaking change which adds functionality)

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️
 I have tested in the local environment

### CODE REVIEW

**Review by singodiyashubham87 — COMMENTED** [review]
Why is this pre.json in images folder?

**Comment by Jagpreet153** [comment]
@singodiyashubham87 pre.json contains the animation in json format

**Comment by singodiyashubham87** [comment]
@Jagpreet153 I understand but it's not an image file. It should be placed under "src/utils/" with the name "preLoaderAnimation.json" & not "pre.json", So that it may provide context of what that JSON is all about.

**Comment by Jagpreet153** [comment]
> @Jagpreet153 I understand but it's not an image file. It should be placed under "src/utils/" with the name "preLoaderAnimation.json" & not "pre.json", So that it may provide context of what that JSON is all about.

Ok I will make these changes

**Comment by singodiyashubham87** [comment]
@Jagpreet153 Additionally, move the Preloader.jsx to the "src/components" directory & not inside the chatbot directory.

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Pull request merged**
