### PR TITLE
jpg, png export types now available

### PR DESCRIPTION
**Pull request by thatsyogeshjjr**
# Issue Title: Additional export options
*resolve issue:* #58 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code style update (formatting, local variables)
 
## How Has This Been Tested? ⚙️

https://github.com/singodiyashubham87/Draw-it-out/assets/69074180/baff63e9-42c8-44e2-8725-a504c911fe7e

### CODE REVIEW

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👀

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Kindly resolve the conflicts.

**Comment by thatsyogeshjjr** [comment]
made some changes, how does it look now @singodiyashubham87 ?

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Looks Good!
Thanks for contributing, Keep up the spirit :)

**Pull request merged**
