### PR TITLE
fixed the breakpoint issue on tablets 

### PR DESCRIPTION
**Pull request by Stiffpixels**
# Issue Title: 
*resolves issue:* #130 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

tested using the responsive developer tool in firefox 

## Video of the fixed issue

https://github.com/singodiyashubham87/Draw-it-out/assets/32983571/67c97091-3e0c-4617-9289-b20f3e212550

### CODE REVIEW

**Review by 0xabdulkhalid — APPROVED** [review]
LGTM 👍🏻

**Comment by singodiyashubham87** [comment]
@Stiffpixels Kindly resolve the conflicts.

**Comment by Stiffpixels** [comment]
> @Stiffpixels Kindly resolve the conflicts.

done

**Comment by Stiffpixels** [comment]
@singodiyashubham87 please merge it

**Comment by 0xabdulkhalid** [comment]
@Stiffpixels, I don't have privileges to Merge PR. 

Please wait for some time, Admin (@singodiyashubham87) will Merge this once he's available.

**Comment by singodiyashubham87** [comment]
@Stiffpixels Thanks for contributing, Keep up the spirit :)

**Pull request merged**
