### PR TITLE
Made website responsive

### PR DESCRIPTION
**Pull request by samarpitadas**
# Issue Title: 
*resolve issue:* #152 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

1. I've added the class sm:w-auto to the anchor (a) tag, which sets its width to auto on small screens and above, allowing it to take the width of its content. This change ensures that the link doesn't stretch too much on smaller screens, maintaining a better layout for screens less than 412px wide.
2. I've changed flex row (flex-row) direction for small (sm) screens and above using sm:flex-row.
3. I've adjusted the spacing between elements using gap-4 for the default and sm:gap-14 for small screens and above.
4. For the buttons inside the inner div, I've adjusted the top margin (mt-4) for small screens only, using sm:mt-0 to reset the margin for screens above 412px wide.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@samarpitadas There are still some fixes that you can do.
> You can position the eye and theme icon below the tool container and also on small screen sizes you can hide the name of the tools like pencil, thickness, etc.
> Also you can hide the coffee icon on screen sizes below md size
image

**Comment by samarpitadas** [comment]
@singodiyashubham87 please do check now. 

1. The hidden md:flex class is added to the button, which ensures that the button is hidden for screen sizes below md. This way, the "Buy me a Coffee" icon will only be visible for medium (md) screen sizes and above.
2.  I've kept the eye icon and dark/light mode buttons in the same flex container as the pencil, color, and thickness options but placed them after these options in the JSX structure. This arrangement ensures they appear below the toolbox containing pencil, color, and thickness for small screen sizes while maintaining horizontal alignment.
3. I have declared a class 'hidden sm:inline'. This is a text span hidden on small screens (sm:inline) but visible on larger screens (hidden).

**Comment by singodiyashubham87** [comment]
@samarpitadas Here is how it's looking on my device, I guess you should check it again.
image

**Comment by singodiyashubham87** [comment]
@samarpitadas Still working on the issue?

**Comment by samarpitadas** [comment]
> @samarpitadas Still working on the issue?

I would like to look into this issue but right now I'm a bit busy with my college work. Could you give me some more time?

**Comment by singodiyashubham87** [comment]
@samarpitadas Okay, giving you more time but try to do it ASAP.

**Comment by singodiyashubham87** [comment]
@samarpitadas I can't give more time, try to resolve the issue by 9th else I would have to unassign you.

**Pull request closed without merging**
