### PR TITLE
Added download button to upload image in Google drive

### PR DESCRIPTION
**Pull request by Bhumika1312**
# Issue Title: No option to save or Export drawings in Google Drive
*closes* #39 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Tested it manually several times. Also, during testing, we have to ensure that the Client ID and Client secret are correct to ensure proper functionality.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@Bhumika1312 Add one more file ".env.example" which will contain the list of environment variables that need to be configured for the application.

**P.S.** : Don't use your API credentials for the variable's value, just put the description of the environment variable like
VITE_CLIENT_ID="GOOGLE_CLIENT_ID"
VITE_API_KEY="GOOGLE_API_KEY"

**Comment by singodiyashubham87** [comment]
@Bhumika1312 Any updates?

**Comment by Bhumika1312** [comment]
Yes @singodiyashubham87 sorry I was having some exams so I'll be updating soon

**Comment by singodiyashubham87** [comment]
@Bhumika1312 Best of luck for exams.

**Comment by Bhumika1312** [comment]
@singodiyashubham87 I have made the changes please review it do tell me if any changes required

**Review by singodiyashubham87 — APPROVED** [review]
Approved!

**Comment by singodiyashubham87** [comment]
@Bhumika1312 Well Done, Keep contributing :)

**Pull request merged**
