### PR TITLE
[FEAT] The canvas is not centered

### PR DESCRIPTION
**Pull request by zaihl**
Fixes: https://github.com/singodiyashubham87/Draw-it-out/issues/246

## Type of change ☑️

What sort of change have you made:
- Centered the canvas
- Adjusted position of Menu component
- Adjusted position of Right panel

## How Has This Been Tested? ⚙️

- Canvas works as normal
- Responsive, works just like before the adjustments

### Before:
Screenshot 2024-06-02 at 20-06-49 Draw it out!
---
### After
Screenshot 2024-06-02 at 19-45-08 Draw it out!

(Raising this for SSOC)

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@zaihl Resolve conflicts.

**Comment by zaihl** [comment]
> @zaihl Resolve conflicts.

done

**Comment by singodiyashubham87** [comment]
@zaihl Merge the main branch & push changes.

**Comment by zaihl** [comment]
It seems again a review is required since there was a conflict. I have resolved it, please review.

**Comment by singodiyashubham87** [comment]
@zaihl Conflict is still there.

**Comment by singodiyashubham87** [comment]
> > @zaihl Merge the main branch & push changes.
> 
> It says that merging is blocked and can be performed automatically with 1 approving review. At least 1 approving review is required by reviewers with write access.

Ignore that warning.

**Comment by singodiyashubham87** [comment]
@zaihl Layout is breaking on small screen sizes.
image

**Pull request closed without merging**
